### ISSUE TITLE
Add README for master branch so that people get what the project is about

### ISSUE THREAD

**Issue by akiss-xyz** [noidawt/tomorrow#6]

**Comment by jordanofoster** [comment]
A basic readme has been added, and contains the following subsections so far:
- A rudimentary guide to building a Visual C++ project with CMake
- Solution to a common problem faced when editing freshly built Visual C++ project (need to add screenshots)

There's obviously room for improvement such as adding guides for building on different systems and with different methods, but for now this should work fine (I imagine those who would want to compile this project with alternative methods likely have the aptitude to do so without a guide, plus you and I are both using VS + CMake for now).

I'm going to close this issue for now, but if any other things need to be added please open up another issue and I'll get round to it when I can.
